_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 4
data:
    value: simulation/data/smoke_v3.h5
device:
    value: null
embed_dim:
    value: 192
frameskip:
    value: 1
grad_clip:
    value: 1
history_size:
    value: 3
img_size:
    value: 128
log_every:
    value: 10
lr:
    value: 5e-05
no_log_file:
    value: false
no_sigreg:
    value: true
num_preds:
    value: 1
num_workers:
    value: 0
overfit_batches:
    value: 4
patch_size:
    value: 16
precision:
    value: fp32
predictor_depth:
    value: 6
predictor_dropout:
    value: 0.1
predictor_heads:
    value: 16
run_name:
    value: wandb_online_smoke
runs_dir:
    value: training/runs
seed:
    value: 3072
sigreg_weight:
    value: 0.09
steps:
    value: 20
wandb:
    value: true
wandb_entity:
    value: 231n-project
wandb_mode:
    value: online
wandb_name:
    value: null
wandb_project:
    value: lewm-smoke
wandb_tags:
    value: smoke,sanity
weight_decay:
    value: 0.001
