_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 128
cache_pixels:
    value: false
compile:
    value: false
data:
    value: simulation/data/rope/rope_full_dataset.h5
device:
    value: null
embed_dim:
    value: 192
frameskip:
    value: 1
git_commit:
    value: e8bdc08b09deb3018f85472833a6958d1694d42c
gpu_cache:
    value: true
grad_clip:
    value: 1
history_size:
    value: 3
img_size:
    value: 128
log_every:
    value: 10
lr:
    value: 5e-05
n_params:
    value: 18023880
no_log_file:
    value: false
no_sigreg:
    value: false
num_preds:
    value: 1
num_workers:
    value: 0
overfit_batches:
    value: 0
patch_size:
    value: 16
precision:
    value: bf16
predictor_depth:
    value: 6
predictor_dim_head:
    value: 64
predictor_dropout:
    value: 0.1
predictor_heads:
    value: 16
run_name:
    value: rope_full_mixed_v1
runs_dir:
    value: training/runs
save_every:
    value: 5000
seed:
    value: 3072
sigreg_weight:
    value: 0.09
steps:
    value: 100000
wandb:
    value: true
wandb_entity:
    value: 231n-project
wandb_mode:
    value: online
wandb_name:
    value: null
wandb_project:
    value: lewm-softgym
wandb_tags:
    value: rope,full_mixed,headline,gpu_cache
weight_decay:
    value: 0.001
